# Generated by Django 6.0.3 on 2026-03-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
