# Generated by Django 6.0.3 on 2026-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
